# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    name: Build wheel for ${{ matrix.python }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo apt-get update
            sudo apt-get install -y libass-dev libjsoncpp-dev
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            # Alternative Windows method using vcpkg
            git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
            C:\vcpkg\bootstrap-vcpkg.bat
            C:\vcpkg\vcpkg install libass
            C:\vcpkg\vcpkg install jsoncpp
          fi
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.8.1
        with:
          output-dir: wheelhouse
        env:
          CIBW_BUILD: "cp${{ matrix.python | replace('.', '') }}-*"
          CIBW_SKIP: "cp34-* cp35-* cp36-*"
          CIBW_ENVIRONMENT_WINDOWS: >
            INCLUDE="C:\vcpkg\installed\x64-windows\include"
            LIB="C:\vcpkg\installed\x64-windows\lib"
          CIBW_ENVIRONMENT: >
            LDFLAGS="-L${VCPKG_ROOT:-/usr/local}/installed/x64-windows/lib"
            CPPFLAGS="-I${VCPKG_ROOT:-/usr/local}/installed/x64-windows/include"

      - name: Show generated wheels
        run: ls wheelhouse

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: built-wheels
          path: ./wheelhouse/*.whl
